In [7]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv("../data/games.csv")
df.head()

,name,rating,released,genres,platforms,metacritic,playtime
0,The Elder Scrolls VI,4.88,NaN,"Action, RPG","PC, Xbox Series S/X",NaN,0
1,"Warhammer 40,000: Dawn of War - Definitive Edi...",4.83,NaN,NaN,PC,NaN,4
2,No Case Should Remain Unsolved,4.83,2024-01-17,"Adventure, Indie","macOS, PC, Nintendo Switch",NaN,3
3,Gimmick!,4.83,1992-01-31,NaN,NES,NaN,0
4,Super Robot Taisen: Original Generation,4.83,2002-11-22,"Action, Strategy",Game Boy Advance,NaN,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1000 non-null   str
 1   rating      1000 non-null   float64
 2   released    976 non-null    str
 3   genres      954 non-null    str
 4   platforms   998 non-null    str
 5   metacritic  403 non-null    float64
 6   playtime    1000 non-null   int64
dtypes: float64(2), int64(1), str(4)
memory usage: 54.8 KB

In [13]:
df.describe()

            rating  metacritic     playtime
count  1000.000000  403.000000  1000.000000
mean      4.438510   85.702233     5.771000
std       0.092757    7.072522    31.014682
min       4.340000   54.000000     0.000000
25%       4.370000   82.500000     0.000000
50%       4.400000   86.000000     0.000000
75%       4.490000   91.000000     4.250000
max       4.880000   99.000000   900.000000